
data = [   {"clsStu": [{"studentID": "1","studentName": "王彤穎"},
                {"studentID": "2","studentName": "鍾尚青"},
                {"studentID": "3","studentName": "許嬈嵐"}],
                "classcode": "CH11201",
                "classcodeId" : 1 ,
                "classroom": "A01",
                "teacher": "王亭潞",
                "subject": "國文" },
    {"clsStu": [{"studentID": "4","studentName": "潘木洪"},
                {"studentID": "5","studentName": "李樂芸"},
                {"studentID": "6","studentName": "曾建琪"}],
                "classcode": "EN11201",
                "classcodeId" : 2 ,
                "classroom": "A01",
                "teacher": "周吉陣",
                "subject": "英文" },
    {"clsStu": [{"studentID": "7","studentName": "石飄飛"},
                {"studentID": "8","studentName": "江川彌"},
                {"studentID": "9","studentName": "顏泓芊"}],
                "classcode": "MA11201",
                "classcodeId" : 3,
                "classroom": "A01",
                "teacher": "薛升言",
                "subject": "數學" } 
];
